# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('max_funcionarios', models.PositiveIntegerField(default=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_funcional', models.PositiveIntegerField(unique=True)),
                ('estado_funcional', models.CharField(choices=[('2', 'Aguardando Vaga'), ('1', 'Contratado'), ('0', 'Demitido')], default='2', max_length=1)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('profissao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('faixa_salarial', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.Pessoa'),
        ),
    ]
